/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ASpace: typeof import('ant-design-vue/es')['Space']
    BasicLayout: typeof import('./src/components/basicLayout/Index.vue')['default']
    BasicLayoutBodyMainContainer: typeof import('./src/components/basicLayout/body/MainContainer.vue')['default']
    BasicLayoutHeaderMenuItem: typeof import('./src/components/basicLayout/header/MenuItem.vue')['default']
    BasicLayoutHeaderNavMenu: typeof import('./src/components/basicLayout/header/NavMenu.vue')['default']
    BasicLayoutHeaderSystemLogo: typeof import('./src/components/basicLayout/header/SystemLogo.vue')['default']
    BasicLayoutHeaderUserInfo: typeof import('./src/components/basicLayout/header/UserInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./src/components/scrollbar/Index.vue')['default']
    Toolbar: typeof import('./src/components/toolbar/Index.vue')['default']
  }
}
